10.10.20.1/28: # would probably use the name here instead, but bin/cluster_conf needs to be fixed to support that
    name: 'example network'
    vdc: 'EXAMPLE_VDC'
    edge: 'nft0000000'
    range:
    - start_address: 10.10.10.2
      end_address: 10.10.10.14
